#!/bin/sh -

workplace="$HOME/workplace"
if [ -n "$PREFIX" ]; then
    bin="$PREFIX/bin"
else
    bin="/usr/local/bin"
fi
function install_agentDoc() {
    ln -sf "${workplace}/agentDoc/agentDoc" "$2" && ln -sf "$2" "$1"
}

install_agentDoc "${bin}/blog" "${workplace}/cf020031308.github.io/blog/.md"
install_agentDoc "${bin}/wk" "${workplace}/cf020031308.github.io/wiki/.md"
