#!/bin/sh -

workplace="$HOME/workplace"
bin="$PREFIX/usr/local/bin"

function install_agentDoc() {
    ln -sf "${workplace}/agentDoc/agentDoc" "$2" && ln -sf "$2" "$1"
}

install_agentDoc "${bin}/atom" "${workplace}/roy.log/blog/.xml"
install_agentDoc "${bin}/wk" "${workplace}/roy.log/wiki/.md"
