#!/bin/bash -
# papis-short-help: Migrate all PDFs out to other places

# if [ -z "$1" ]; then
#     echo "Missing Argument: papis migrate-pdf [DESTINATION FOLDER]"
#     exit 1
# fi
# cd $1 || exit 0
# dst=$(pwd)

PAPIS_LIB=cs
dst="/Users/Roy/Documents/papers"
pdfs=$(papis -l ${PAPIS_LIB} export --json --all 2>&- | jq -r '.[] | .files | .[]? | select(test("\\.pdf$"))' | sed '/^\//d' | sort -u)
dir="$(papis -l ${PAPIS_LIB} config dir)"
dir="${dir/\~/$HOME}"
for pdf in $pdfs; do
    for pdf_src in $(find "$dir" -type f -name "$pdf"); do
        pdf_dir=$(dirname $pdf_src)
        pdf_dst="$dst/$(basename $pdf_dir).pdf"
        mv "$pdf_src" "$pdf_dst" && sed -i '' "s;^- $pdf$;- $pdf_dst;" "$pdf_dir/info.yaml"
        BaiduPCS-Go upload "$pdf_dst" "/文档/papers/"
    done
done
