#!/bin/sh -
# > https://github.com/zegervdv/homebrew-zathura

brew tap zegervdv/zathura
brew install cask xquartz
brew install zathura zathura-pdf-poppler

mkdir -p $(brew --prefix zathura)/lib/zathura
ln -s $(brew --prefix zathura-pdf-poppler)/libpdf-poppler.dylib $(brew --prefix zathura)/lib/zathura/libpdf-poppler.dylib

ln -s "$PWD" ~/.config/
