# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.linked_clone = true
  end
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "~/Workplace", "/home/vagrant/workplace"
  config.vm.provision :shell, path: "./provision.sh"

  config.vm.define "dev", autostart: false do |dev|
      config.vm.hostname = "DevRoy"
      config.vm.provision :shell, path: "./dev/provision.sh"
  end

end
