#!/bin/bash -

PUBLIC="$PWD"
PRIVATE="$HOME/Nutstore/mail"

ln -sf $PUBLIC ~/.mail
ln -sf $PRIVATE/muttrc ~/.muttrc
ln -sf $PRIVATE/offlineimaprc ~/.offlineimaprc
ln -sf $PRIVATE/msmtprc ~/.msmtprc


brew install offlineimap msmtp mutt lynx
